# Use vi-style keys in copy mode
set-option -g mode-keys vi

set -g mouse on

# Enable xterm keys for Ghostty
set -g xterm-keys on

# Easier resize bindings (Vim-style)
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Arrow key bindings
bind -r C-Left  resize-pane -L 5
bind -r C-Right resize-pane -R 5
bind -r C-Up    resize-pane -U 5
bind -r C-Down  resize-pane -D 5

